### ISSUE TITLE
Is there a vscode intergration for this?

### ISSUE THREAD

**Issue by palash25** [alexkohler/nargs#1]
It would be nice to have a vscode extension for this

**Comment by alexkohler** [comment]
There is not a direct vscode integration, however, you could request that [golangci-lint](https://github.com/golangci/golangci-lint) guys add `nargs` as a supported linter.

There [is also a Wiki page for adding a custom linter to golangci-lint](https://github.com/golangci/golangci-lint/wiki/How-to-add-a-custom-linter).

**Comment by palash25** [comment]
Thanks for that, raised an issue on their repo https://github.com/golangci/golangci-lint/issues/553
